// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var aYearAgo, now, svg,
      _this = this;
    console.log("Started");
    now = moment();
    aYearAgo = now.subtract('years', 1);
    console.dir(aYearAgo);
    _.mixin({
      extractStartOfDay: function(items, datePropertyReader) {
        var format,
          _this = this;
        format = d3.time.format("%Y-%m-%d");
        return _.map(items, function(item) {
          var m, startOfDay;
          m = moment(datePropertyReader(item));
          startOfDay = m.startOf('day');
          item['day'] = format(startOfDay.toDate());
          return item;
        });
      }
    });
    svg = dimple.newSvg("#chartContainer", 620, 600);
    return d3.json("/js/data/weight.json", function(weightData) {
      return d3.json("/js/data/fitnessActivities.json", function(activityData) {
        var activityItems, myChart, weightItems, x1, x2, y1, y2;
        weightItems = _.chain(weightData.items).filter(function(i) {
          return i.weight > 50;
        }).filter(function(i) {
          return moment(i.timestamp).isAfter(aYearAgo);
        }).extractStartOfDay(function(item) {
          return item.timestamp;
        }).value();
        console.dir(weightItems);
        activityItems = _.chain(activityData.items).filter(function(i) {
          return moment(i.start_time).isAfter(aYearAgo);
        }).extractStartOfDay(function(item) {
          return item.start_time;
        }).value();
        console.dir(activityItems);
        myChart = new dimple.chart(svg, weightItems);
        myChart.setBounds(60, 30, 505, 305);
        x1 = myChart.addTimeAxis("x", "timestamp", null, "%Y-%m-%d");
        x1.addOrderRule("Date");
        x2 = myChart.addTimeAxis("x", "start_time", null, "%Y-%m-%d");
        x2.addOrderRule("Date");
        y1 = myChart.addMeasureAxis("y", "weight");
        y1.overrideMin = 80;
        myChart.addSeries(null, dimple.plot.line, [x1, y1]);
        y2 = myChart.addMeasureAxis("y", "total_calories");
        myChart.addSeries(null, dimple.plot.bar, [x2, y2]);
        return myChart.draw();
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
