// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var svg,
      _this = this;
    console.log("Started");
    svg = dimple.newSvg("#chartContainer", 590, 500);
    return d3.json("/js/data/snapshot.json", function(data) {
      var aYearAgo, items, myChart, now, s, x, y;
      now = moment();
      aYearAgo = now.subtract('years', 1);
      console.dir(aYearAgo);
      items = data.items.filter(function(i) {
        return i.weight > 50;
      }).filter(function(i) {
        return moment(i.timestamp).isAfter(aYearAgo);
      });
      myChart = new dimple.chart(svg, items);
      myChart.setBounds(60, 30, 505, 305);
      x = myChart.addTimeAxis("x", "timestamp", null, "%Y-%m-%d");
      x.addOrderRule("Date");
      y = myChart.addMeasureAxis("y", "weight");
      y.overrideMin = 80;
      s = myChart.addSeries(null, dimple.plot.line);
      return myChart.draw();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
